const dummyPeople = [
    { id: 1, name: 'Aanya Patel', branch: 'Computer Science', year: '2022', description: 'ML Engineer at Tesla', avatar: 'https://randomuser.me/api/portraits/women/1.jpg' },
    { id: 2, name: 'Rohan Sharma', branch: 'Electronics', year: '2021', description: 'Hardware Designer at Intel', avatar: 'https://randomuser.me/api/portraits/men/2.jpg' },
    { id: 3, name: 'Neha Gupta', branch: 'IT', year: '2023', description: 'Full Stack Dev at Microsoft', avatar: 'https://randomuser.me/api/portraits/women/3.jpg' },
    { id: 4, name: 'Arjun Mehta', branch: 'Mechanical', year: '2020', description: 'Design Engineer at Boeing', avatar: 'https://randomuser.me/api/portraits/men/4.jpg' },
    { id: 5, name: 'Priya Verma', branch: 'Civil', year: '2024', description: 'Urban Planner Intern', avatar: 'https://randomuser.me/api/portraits/women/5.jpg' },
    { id: 6, name: 'Siddharth Jain', branch: 'Chemical', year: '2021', description: 'Researcher at Reliance Industries', avatar: 'https://randomuser.me/api/portraits/men/6.jpg' },
    { id: 7, name: 'Kavya Desai', branch: 'Computer Science', year: '2022', description: 'Frontend Developer at Adobe', avatar: 'https://randomuser.me/api/portraits/women/7.jpg' },
    { id: 8, name: 'Aditya Nair', branch: 'IT', year: '2020', description: 'Cloud Architect at AWS', avatar: 'https://randomuser.me/api/portraits/men/8.jpg' },
    { id: 9, name: 'Simran Kaur', branch: 'Electronics', year: '2023', description: 'Embedded Systems Engineer', avatar: 'https://randomuser.me/api/portraits/women/9.jpg' },
    { id: 10, name: 'Rahul Dutta', branch: 'Mechanical', year: '2019', description: 'Automation Engineer at Siemens', avatar: 'https://randomuser.me/api/portraits/men/10.jpg' },
    { id: 11, name: 'Meera Joshi', branch: 'Electrical', year: '2021', description: 'Power Systems Analyst', avatar: 'https://randomuser.me/api/portraits/women/11.jpg' },
    { id: 12, name: 'Devansh Kapur', branch: 'IT', year: '2022', description: 'Cybersecurity Specialist', avatar: 'https://randomuser.me/api/portraits/men/12.jpg' },
    { id: 13, name: 'Anjali Thakur', branch: 'Civil', year: '2023', description: 'Architectural Intern', avatar: 'https://randomuser.me/api/portraits/women/13.jpg' },
    { id: 14, name: 'Tushar Vyas', branch: 'Computer Science', year: '2021', description: 'Backend Developer at Google', avatar: 'https://randomuser.me/api/portraits/men/14.jpg' },
    { id: 15, name: 'Nisha Rana', branch: 'Electronics', year: '2020', description: 'IoT Engineer at Honeywell', avatar: 'https://randomuser.me/api/portraits/women/15.jpg' },
    { id: 16, name: 'Aryan Bhatt', branch: 'IT', year: '2022', description: 'DevOps Engineer at Netflix', avatar: 'https://randomuser.me/api/portraits/men/16.jpg' },
    { id: 17, name: 'Ritika Malhotra', branch: 'Computer Science', year: '2024', description: 'UI/UX Designer Intern', avatar: 'https://randomuser.me/api/portraits/women/17.jpg' },
    { id: 18, name: 'Mohit Singh', branch: 'Mechanical', year: '2020', description: 'Product Designer at Ford', avatar: 'https://randomuser.me/api/portraits/men/18.jpg' },
    { id: 19, name: 'Ankita Goyal', branch: 'Chemical', year: '2021', description: 'Process Engineer at ONGC', avatar: 'https://randomuser.me/api/portraits/women/19.jpg' },
    { id: 20, name: 'Varun Raj', branch: 'Electrical', year: '2023', description: 'Control Systems Engineer', avatar: 'https://randomuser.me/api/portraits/men/20.jpg' },
    { id: 21, name: 'Divya Rathi', branch: 'IT', year: '2022', description: 'QA Analyst at Zomato', avatar: 'https://randomuser.me/api/portraits/women/21.jpg' },
    { id: 22, name: 'Yash Khanna', branch: 'Computer Science', year: '2021', description: 'AI Researcher at OpenAI', avatar: 'https://randomuser.me/api/portraits/men/22.jpg' },
    { id: 23, name: 'Sneha Rawat', branch: 'Civil', year: '2024', description: 'Infrastructure Intern', avatar: 'https://randomuser.me/api/portraits/women/23.jpg' },
    { id: 24, name: 'Rajat Tiwari', branch: 'Electronics', year: '2022', description: 'FPGA Designer', avatar: 'https://randomuser.me/api/portraits/men/24.jpg' },
    { id: 25, name: 'Mitali Sharma', branch: 'Computer Science', year: '2023', description: 'SDE Intern at Flipkart', avatar: 'https://randomuser.me/api/portraits/women/25.jpg' },
    { id: 26, name: 'Arnav Reddy', branch: 'IT', year: '2020', description: 'Security Engineer at Cisco', avatar: 'https://randomuser.me/api/portraits/men/26.jpg' },
    { id: 27, name: 'Tanvi Iyer', branch: 'Chemical', year: '2021', description: 'Analyst at P&G', avatar: 'https://randomuser.me/api/portraits/women/27.jpg' },
    { id: 28, name: 'Nikhil Jaiswal', branch: 'Mechanical', year: '2022', description: 'Thermal Engineer at ISRO', avatar: 'https://randomuser.me/api/portraits/men/28.jpg' },
    { id: 29, name: 'Sanya Bhatia', branch: 'Electrical', year: '2023', description: 'Circuit Designer at Intel', avatar: 'https://randomuser.me/api/portraits/women/29.jpg' },
    { id: 30, name: 'Aman Verma', branch: 'Computer Science', year: '2021', description: 'Software Engineer at Paytm', avatar: 'https://randomuser.me/api/portraits/men/30.jpg' },
    { id: 31, name: 'Isha Kapoor', branch: 'IT', year: '2020', description: 'Data Analyst at Swiggy', avatar: 'https://randomuser.me/api/portraits/women/31.jpg' },
    { id: 32, name: 'Rudra Patel', branch: 'Electronics', year: '2022', description: 'Embedded Developer at Qualcomm', avatar: 'https://randomuser.me/api/portraits/men/32.jpg' },
    { id: 33, name: 'Pooja Singh', branch: 'Civil', year: '2024', description: 'Environment Engineer Intern', avatar: 'https://randomuser.me/api/portraits/women/33.jpg' },
    { id: 34, name: 'Karan Joshi', branch: 'Mechanical', year: '2020', description: 'Project Engineer at Tata Motors', avatar: 'https://randomuser.me/api/portraits/men/34.jpg' },
    { id: 35, name: 'Shruti Aggarwal', branch: 'Computer Science', year: '2022', description: 'App Developer at Swiggy', avatar: 'https://randomuser.me/api/portraits/women/35.jpg' },
    { id: 36, name: 'Viraj Kulkarni', branch: 'IT', year: '2021', description: 'Scrum Master at Infosys', avatar: 'https://randomuser.me/api/portraits/men/36.jpg' },
    { id: 37, name: 'Pallavi Rao', branch: 'Electronics', year: '2023', description: 'Signal Processing Intern', avatar: 'https://randomuser.me/api/portraits/women/37.jpg' },
    { id: 38, name: 'Dev Patel', branch: 'Electrical', year: '2021', description: 'Power Engineer at L&T', avatar: 'https://randomuser.me/api/portraits/men/38.jpg' },
    { id: 39, name: 'Suhani Dixit', branch: 'IT', year: '2022', description: 'Blockchain Dev at Polygon', avatar: 'https://randomuser.me/api/portraits/women/39.jpg' },
    { id: 40, name: 'Ishaan Mahajan', branch: 'Chemical', year: '2020', description: 'Lab Chemist at BASF', avatar: 'https://randomuser.me/api/portraits/men/40.jpg' },
  ];

  export default dummyPeople;